#!/usr/bin/python

while True:
    print("==========================")
    print("1) Read and display names ")
    print("2) Add new name")
    print("3) Exit")
    print("==========================")
    print()
    user_input = input('Choose a option: ')

    if user_input == '1':
     file = open("names.txt", "r")
     print(/n)
     print(file.read())

    elif user_input == '2':
     print('2')

    else:
     print('Exiting...')
     break


